Repository hashgraph/hedera-forking, pull requests merged in 2025-02, with the labels that each got.

#209 feat: example usage in nft testing of our foundry library and hardhat plugin (#191)
  contracts/HtsSystemContractJson.sol
  examples/foundry-hts/NFT.t.sol
  examples/foundry-hts/NFTConsole.t.sol
  examples/hardhat-hts/contracts/CallNFT.sol
  examples/hardhat-hts/contracts/IERC721.sol
  examples/hardhat-hts/package-lock.json
  examples/hardhat-hts/test/nft-info.test.js
  examples/hardhat-hts/test/nft-ownerof.test.js
  examples/hardhat-hts/test/nft-transfer.test.js
  examples/hardhat-hts/test/nft.test.js
  src/forwarder/mirror-node-client.js
  src/slotmap.js
Labels: feature

#229 feat: export Solidity interfaces
  contracts/HtsSystemContract.sol
  contracts/IERC20.sol
  contracts/IERC721.sol
  examples/foundry-hts/NFT.t.sol
  examples/foundry-hts/NFTConsole.t.sol
  examples/foundry-hts/USDC.t.sol
  examples/foundry-hts/USDCConsole.t.sol
  examples/hardhat-hts/contracts/CallNFT.sol
  examples/hardhat-hts/contracts/CallToken.sol
  examples/hardhat-hts/contracts/IERC20.sol
  examples/hardhat-hts/contracts/IERC721.sol
  examples/hardhat-hts/test/usdc.test.js
  test/ERC20.t.sol
  test/ERC721.t.sol
  test/HTS.t.sol
  test/plugin/fork-block-project/IERC20.sol
  test/plugin/fork-block-project/test.js
  test/plugin/hedera-fork-project/IERC20.sol
  test/plugin/hedera-fork-project/test.js
Labels: feature

#224 feat: making gettokeninfo and its dependants a view function (#164)
  contracts/HtsSystemContract.sol
  contracts/IHederaTokenService.sol
  examples/foundry-hts/USDC.t.sol
  test/HTS.t.sol
Labels: feature

#223 fix: returning non-success response code instead of reverting when supplykey is missing (#167)
  contracts/HederaResponseCodes.sol
  contracts/HtsSystemContract.sol
  contracts/KeyLib.sol
  test/HTS.t.sol
  test/hts.e2e.js
Labels: bug

#222 feat: returning correct ledger id in tokeninfo (#163)
  contracts/HtsSystemContractJson.sol
  src/forwarder/index.js
  src/forwarder/json-rpc-forwarder.js
  src/index.d.ts
  src/index.js
  src/plugin/index.js
  src/slotmap.js
  test/HTS.t.sol
  test/forwarder.test.js
  test/hts.e2e.js
  test/slotMapOf.test.js
Labels: feature

#239 docs: add badges to `README`
  README.md
Labels: docs

#241 docs: add FAQ document to list common forking issues
  FAQ.md
  README.md
Labels: docs

#243 feat: isassociated method will revert for non-existing accounts (#242)
  contracts/HtsSystemContract.sol
  contracts/HtsSystemContractJson.sol
  src/index.js
  test/HTS.t.sol
  test/IHRC719.t.sol
  test/data/getAccount_0x0000000000000000000000000000000000001438.json
  test/getHtsStorageAt.test.js
  test/hts.e2e.js
Labels: feature
