Repository hashgraph/hedera-forking, pull requests merged in 2025-01, with the labels that each got.

#157 test: include e2e to validate HTS emulation against real HTS
  INTERNALS.md
  README.md
  contracts/MirrorNodeFFI.sol
  package-lock.json
  package.json
  scripts/create-token.js
  src/forwarder/index.js
  src/forwarder/json-rpc-forwarder.js
  src/forwarder/mirror-node-client.js
  src/plugin/hardhat-addresses.js
  src/plugin/index.d.ts
  src/plugin/index.js
  test/.anvil.js
  test/anvil.test.js
  test/forwarder.test.js
  test/hts.e2e.js
  tsconfig.json
Labels: docs, test, dependencies

#169 feat: include JSON compiled output in version control
  .gitignore
  examples/hardhat-hts/README.md
  examples/hardhat-hts/hardhat.config.js
  examples/hardhat-hts/package-lock.json
  examples/hardhat-hts/package.json
  out/HtsSystemContract.sol/HtsSystemContract.json
Labels: build

#176 build: add workflow publish to npm
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
Labels: github-actions, build

#173 feat: [Hardhat] implement nft support for the json rpc api library and js mock …
  .github/workflows/test.yml
  src/forwarder/mirror-node-client.js
  src/index.d.ts
  src/index.js
  src/slotmap.js
  test/getHtsStorageAt.test.js
  test/scripts/json-rpc-mock.js
Labels: feature

#183 feat: avoid fetching code for `console.log` address
  src/forwarder/json-rpc-forwarder.js
Labels: feature

#181 build: add release notes configuration
  .github/release.yml
Labels: github-actions, build

#190 docs: include ERC721 supported methods in `README`
  README.md
  scripts/abi-table.js
Labels: docs

#187 chore: fix codeowners for workflows dir
  .github/CODEOWNERS
Labels: Audit

#214 chore: fix Anvil test
  .github/workflows/test.yml
Labels: build

#208 chore: update codeowners
  .github/CODEOWNERS
Labels: build

#211 feat: implementation of `transferTokens` method (#200)
  contracts/HtsSystemContract.sol
  contracts/IHederaTokenService.sol
  test/HTS.t.sol
Labels: feature

#220 feat: [Foundry] implement `create*FungibleToken*`
  CREATE_TOKEN.md
  contracts/HtsSystemContract.sol
  contracts/HtsSystemContractJson.sol
  contracts/IHederaTokenService.sol
  contracts/SetTokenInfo.sol
  test/CreateToken.t.sol
  test/ERC20.t.sol
  test/HTS.t.sol
  test/getHtsStorageAt.test.js
Labels: feature

#215 fix: emit correct transfer and approval events (#194)
  README.md
  contracts/HtsSystemContract.sol
  contracts/IERC20.sol
  contracts/IERC721.sol
  test/ERC721.t.sol
  test/HTS.t.sol
Labels: bug
